# netlify.toml (new, at project root)

[[headers]]
for = "/data/icao-to-name.json"
  [headers.values]
  Cache-Control = "public, max-age=31536000"
  Surrogate-Control = "max-age=31536000"

[build]
publish = "."

